[package]
name = "md-numbered-headers"
version = "0.2.0"
authors = ["Taiki Ono <m@taiki.dev>"]
edition = "2018"
description = "Read a markdown file from STDIN then add numbers in headers then output to STDOUT."

[dependencies]
regex = "1"
lazy_static = "1.4.0"
structopt = "0.3"
